swagger: '2.0'
info:
  title: 'THE WALL API documentation'
  version: '1.0'
host: 'api-staging.arttrend.asia'
basePath: '/'
schemes:
  - 'https'
consumes:
  - 'application/json'
produces:
  - 'application/json'
tags:
  -
    name: 藝人
