swagger: 2.0
info:
  title: 'THE WALL API documentation'
  version: '1.0'
host: 'api-staging.thewall.tw'
basePath: '/'
schemes:
  - 'https'
consumes:
  - 'application/json'
produces:
  - 'application/json'
tags:
  -
    name: 藝人
paths:
  /artists':
    get:
      summary: '取得所有藝人列表'
      tags:
        - 藝人
      description: '取得所有藝人列表'
      operationId: 'artists_index'
      responses:
        '200':
          description: ''
  /artists/{artist_id}:
    get:
      summary: '取得藝人基本資料'
      tags:
        - 藝人
      description: '取得藝人基本資料'
      operationId: 'artists_show'
      parameters:
        -
          name: 'artist_id'
          in: path
          required: true
          type: integer
          description: '藝人 ID'
          allowEmptyValue: false
      responses:
        '200':
          description: ''
